### ISSUE TITLE
Can't list manifest module params

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-ledger#19]
I'm unable to list the manifest module parameters on the testnet.

```shell
$ manifestd q manifest params --node tcp://[TESTNET_IP]:21157 --chain-id manifest-1
rpc error: code = Unknown desc = unknown query path: unknown request
```

where TESTNET_IP is the public IP of the RPC server.

I tested with another module and it worked as expected.

**Comment by Reecepbcups** [comment]
@fmorency Please make sure you are using the latest manifestd binary (using either main or the tagged versions). Older versions of the binary are not compatible. Chain-ID is also not used in queries, and this testnet is `obvious-1` if it was

```
manifestd q manifest params --node=http://66.172.36.142:21157
```

![image](https://github.com/liftedinit/manifest-ledger/assets/31943163/eaaf3c2d-fbe5-4be7-893c-e6804058ee16)

**Comment by fmorency** [comment]
That did it! Thanks @Reecepbcups
