### ISSUE TITLE
No error when payout amount is too small

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-ledger#27]
A payout transaction will go through without error even if the amount to be distributed is too small.

Open `script/test_node.sh` and modify the `manifest` section with

```bash
update_test_genesis '.app_state["manifest"]["params"]["inflation"]["mint_denom"]="umfx"'
update_test_genesis '.app_state["manifest"]["params"]["inflation"]["yearly_amount"]="0"' # in micro format (1MFX = 10**6)
update_test_genesis '.app_state["manifest"]["params"]["inflation"]["automatic_enabled"]=false'
update_test_genesis '.app_state["manifest"]["params"]["stake_holders"]=[{"address":"manifest1hj5fveer5cjtn4wd6wstzugjfdxzl0xp8ws9ct","percentage":100000000}]'
```

to disable automatic inflation and set the yearly amount to 0.

Next, 
```shell
# Start a new test node
POA_ADMIN_ADDRESS=manifest1hj5fveer5cjtn4wd6wstzugjfdxzl0xp8ws9ct CHAIN_ID="local-1" HOME_DIR="~/.manifest" TIMEOUT_COMMIT="500ms" CLEAN=true sh scripts/test_node.sh

# Update the `manifest` module parameters
manifestd --keyring-backend test --chain-id local-1 tx manifest update-params manifest1efd63aw40lxf3n4mhf7dzhjkr453axurm6rp3z:50_000_000,manifest17dh4tstgw4s30ht4lfuc2l6gccqkzttxylw8kq:25_000_000,manifest1gp33pgpx78j7lgjm4422tp80uaxseap6m8fd6s:25_000_000 false 0umfx --from user1
```

Verify the balances of each accounts
```shell
manifestd q bank balance manifest1hj5fveer5cjtn4wd6wstzugjfdxzl0xp8ws9ct umfx                        
balance:
  amount: "10000000"
  denom: umfx

manifestd q bank balance manifest1gp33pgpx78j7lgjm4422tp80uaxseap6m8fd6s umfx
balance:
  amount: "0"
  denom: umfx

manifestd q bank balance manifest17dh4tstgw4s30ht4lfuc2l6gccqkzttxylw8kq umfx
balance:
  amount: "0"
  denom: umfx

manifestd q bank balance manifest1efd63aw40lxf3n4mhf7dzhjkr453axurm6rp3z umfx
balance:
  amount: "100000"
  denom: umfx
```

and try the following payout to stakeholders
```shell
manifestd --chain-id local-1 --keyring-backend test tx manifest stakeholder-payout 1umfx --from user1
```

Notice that the transaction went through without error. The balances of each account remain unchanged.

I would expect an error if the payout is too small, i.e., can't be distributed across all stakeholders.

**Comment by chalabi2** [comment]
This assumes a couple things about the state of the genesis file and the specific parameter you are referring to post chain launch. 

1. the starting amount in the genesis is set to 0

2. the PoA admin approves a change to 0 

I don't think either of those would ever be true. That being said it shouldn't be too tough to add some sort of handling for this specific case.

**Comment by fmorency** [comment]
> This assumes a couple things about the state of the genesis file and the specific parameter you are referring to post chain launch.
> 
>     1. the starting amount in the genesis is set to 0
> 
>     2. the PoA admin approves a change to 0
> 
> 
> I don't think either of those would ever be true. That being said it shouldn't be too tough to add some sort of handling for this specific case.

I'm not sure I understand what you mean by that.

If you're talking about the yearly amount, it doesn't matter as automatic inflation is disabled. I can reproduce the issue by leaving the amount to the original value.

**Comment by chalabi2** [comment]
@Reecepbcups Does the yearly amount not matter when you are manually minting?

**Comment by Reecepbcups** [comment]
This edge case only applies when sending such a small amount from the multisig (i.e. n-1 umfx where n is the number of stakeholders to payout). If small meaningless transactions are planned to be signed by the team, then this is something that should error. But I never forsaw the team sending transactions so microscopic (0.000001 per user) that the gas would be a few thousand times more costly than the actual Tx distributes.

**Comment by chalabi2** [comment]
@fmorency, is this actually a situation we will find in main-net? The chain is controlled by the team, does the team plan on sending pointless transactions like this?

**Comment by fmorency** [comment]
@chalabi2 I don't think so, at least not intentionally.

This is a low-priority issue. This is not a blocking issue unless you tell me it would be hard to fix after release.
