### ISSUE TITLE
Remove unused modules from client app

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-ledger#31]
The current chain exposes unused modules such as `nft`. 

Unregister unused modules from the client to keep the list to a minimum and reduce the attack surface of the chain.

**Comment by Reecepbcups** [comment]
@fmorency NFT is connected? This adds support for ICS-721 which is an IBC specification which can be found [HERE](https://github.com/cosmos/ibc/blob/main/spec/app/ics-721-nft-transfer/README.md)

If this support is not desired I am fine to remove it, but the module is used in the client app `manifestd q nft`

**Comment by chalabi2** [comment]
@fmorency 

https://github.com/liftedinit/manifest-ledger/releases/tag/v0.0.1-alpha.3
