### ISSUE TITLE
Fix CodeQL advisory

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-ledger#38]
There are a bunch of CodeQL advisories at https://github.com/liftedinit/manifest-ledger/security/code-scanning.

The "Panic in BeginBock or EndBlock consensus methods" and "Iteration over map" sounds especially scary.

**Comment by Reecepbcups** [comment]
These are false positives. Sound scary, but the analyse does not have context into how it works behind the scenes on the SDK side. false positives for our cases

- you can iter over a map so long as you don't break early
- yes Begin/End blockers can panic, but should only happen when something is really wrong (i.e. no params at all). Nothing can be done, it's an sdk thing

**Comment by fmorency** [comment]
For the sake of posterity, iterating over a map is **non-deterministic** in Go.

See https://github.com/liftedinit/manifest-ledger/issues/48
