### ISSUE TITLE
Add support for burning native tokens

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-ledger#63]
@Reecepbcups, do we have the means to burn native tokens, e.g., `umfx`?

I tried using the `MsgBurn` from the `tokenfactory` module where the sender is the POA admin but it failed with

```
"proposal execution failed on proposal 4, because of error message /osmosis.tokenfactory.v1beta1.MsgBurn at position 0: unauthorized account"
```

I haven't found anything in the `x/bank` module to allow burning native tokens and my research in the Cosmos repo came back empty-handed.

**Comment by Reecepbcups** [comment]
Tokenfactory can only burn tokens from the tokenfactory module itself. umfx is not

Does not look like SDK v50 has a burn, but it is in main :\. We could add a simple command in manifest module to bank.Burn() umfx from a senders held balance if you want
![image](https://github.com/liftedinit/manifest-ledger/assets/31943163/eb1c489a-c349-4bec-8465-928bf02809e4)

**Comment by fmorency** [comment]
That's what I thought, thanks for confirming. 

Yes, adding a simple command in the manifest module until we upgrade to 0.51 would be great. I will change the title of this ticket to track it.

Thanks @Reecepbcups
